### ISSUE TITLE
Suggestions for "My scan" => "Favorites"

### ISSUE THREAD

**Issue by TradingDominion** [ninjaspread/ns#1]
Suggestions for "My scan" => "Favorites":

- clicking on any favorite item should load up that particular scan
- add a visual cue to show which favorite item has alerts enabled
- add the ability to enable/disable alert functionality from that table view

**Comment by ninjaspread** [comment]
Thank you for your suggestions. Everything is done and ready to use.

**Comment by TradingDominion** [comment]
I see that you've added the alerts notification to each favorite item, which is great.

With regards to clicking on the favorite item itself, it currently opens up a new row beneath it which allows you to delete that entry.
It would be useful to be able to click on the favorite item, and have that load up that particular search and automatically fill in all of the search values based on the list defined in the favorite.

For deleting favorites, it would be better to be able to have a checkbox on the left of each favorite item so that we could potentially select multiple favorites at one time and delete them in one step by then clicking on a delete action button.

**Comment by ninjaspread** [comment]
- I fixed the name issue, now you can click on it, and will redirect to your own scan.
- The thing about opening up a new row is because the table was too wide to be displayed. What was the screen resolution of your monitor when you checked it? Now I have disabled columns that are not a must to see here so you will see the complete table without the need to expand it.
- now there is a delete button at the end of the row. I get the suggestion that it should be able to be deleted multiple at once.
